config/routes.rb
Rails.application.routes.draw do
  get 'operations/index'
  get 'user/index'
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users
  resources :operations
  resources :categories, only: [:index, :show, :new, :create] do
    get 'operations', to: 'operations#index', as: 'operations'
  end
  # Defines the root path route ("/")
  # root "articles#index"
  get '/', to: 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :category
  belongs_to :operation
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :categorizations, dependent: :destroy
  has_many :operations, through: :categorizations

  validates :user_id, presence: true

  def slug
    name.parameterize
  end

  def total_amount
    operations.sum(:amount)
  end

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :icon, presence: true
end

app/models/category_operation.rb
class CategoryOperation < ApplicationRecord
  belongs_to :category
  belongs_to :operations
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :category
  belongs_to :user
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  before_save :set_user_id

  private

  def set_user_id
    self.user_id = author_id
  end

  validates :name, :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :authored_operations, class_name: 'Operation', foreign_key: 'author_id'
  has_many :categories
  has_many :operations

  validates :name, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :name) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:email, :password, :current_password, :name)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :redirect_unauthenticated_user_to_custom_page

  def index
    @categories = current_user.categories.includes(:operations)
    @operations_by_category = {}
    @categories.each do |category|
      operations = Operation.where(category_id: category.id)
      @operations_by_category[category.id] = operations
    end

    @total_amount_by_category = {}
    @categories.each do |category|
      operations = @operations_by_category[category.id]
      @total_amount_by_category[category.name] = operations.sum(:amount)
    end
    @page_name = 'Categories'
  end

  def show
    @category = Category.includes(:operations).find(params[:id])
    @operations = @category.operations
    @total_amount = @operations.sum(:amount)
    @page_name = 'Categories'
  end

  def new
    @category = Category.new
    @page_name = 'New Category'
  end

  def create
    @category = current_user.categories.build(category_params)

    if Category.exists?(name: @category.name, user_id: current_user.id)
      flash[:notice] = 'Category already exists'
      render :new
    elsif @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon, :user_id)
  end

  def redirect_unauthenticated_user_to_custom_page
    return if user_signed_in?

    redirect_to '/users/'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :redirect_unauthenticated_user_to_custom_page

  def index
    if params[:category_id].present?
      @category = Category.find(params[:category_id])
      @operations = current_user.operations.includes(:category).where(category: @category)
      @total_amount = @operations&.sum(:amount) || 0
    else
      @operations = current_user.operations
    end
    @page_name = 'Transactions'
  end

  def new
    @operation = current_user.operations.build
    @categories = current_user.categories
    @category = Category.find(params[:category_id]) if params[:category_id].present?
    @page_name = 'Transactions'
  end

  def create
    @operation = current_user.operations.build(operation_params)
    @categories = current_user.categories
    @category = Category.find(params[:operation][:category_id]) if params[:operation][:category_id].present?
    @operation.category = @category
    if @operation.save
      Categorization.create(operation: @operation, category: @category)
      redirect_to category_operations_path(@operation.category)
    else
      puts @operation.errors.full_messages
      render :new
    end
  end

  private

  def operation_params
    params.require(:operation).permit(:name, :amount, :category_id, :author_id)
  end

  def redirect_unauthenticated_user_to_custom_page
    return if user_signed_in?

    redirect_to '/users/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def emojis
    ['💵', '💸', '💳', '📚', '🍔', '🍕', '🍎', '☕️', '🍸', '✈️', '🚆', '🛵', '🚲', '🏝️', '🛴', '👑', '💻', '📈', '🎓', '💼', '🎸', '⚽',
     '🏀', '🚗', '🏨', '🐶', '🐱', '🔧']
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/categories/index.html.erb
<div class="w-full mb-12 overflow-x-hidden overflow-y-hidden">
<% @categories.each do |category| %>
  <%= link_to category_operations_path(category_id: category.id), class: "grid grid-cols-3 gap-5 w-screen p-4 my-2 justify-between bg-white" do %>
        <div class="text-4xl flex justify-center items-center bg-yellow-100 h-16 w-16 text-center">
          <%= category.icon %>
        </div>
        <p><%= category.name %></p>
        <p class="flex justify-end font-semibold"><%= number_to_currency(@total_amount_by_category[category.name]) %></p>
  <% end %>
<% end %>
</div>
<div class="fixed bottom-0 w-full bg-lime-600 text-center hover:bg-lime-700 py-6">
<%= link_to "New Category", new_category_path, class: "text-white py-4 border-2 border-white" , style: "padding-left: 32%; padding-right: 32%;" %>
</div>

app/views/categories/new.html.erb
<div class="flex flex-col items-center w-full">

<%= form_with(model: @category, local: true, html: { class: "w-full flex flex-col" }) do |form| %>
  

  <div class="field">
    <%= form.text_field :name, placeholder: "Name", class: "mt-4 mb-2 block w-full border-1 border-slate-50 bg-white focus:ring focus:ring-gray-200 focus:ring-opacity-50" %>
  </div>

  <div class="field flex flex-col m-2">
  <%= form.label :icon %>
  <%= form.collection_select :icon, emojis, :itself, :itself %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions fixed bottom-0 w-full bg-lime-600 text-center hover:bg-lime-700 py-2 text-white">
    <%= form.submit 'Save', class: 'text-white py-4 border-2 border-white', style: "padding-left: 43%; padding-right: 43%;" %>
  </div>
<% end %>

</div>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<% puts @operations.inspect %>
<% if @operations.any? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      <% @operations.each do |operation| %>
        <tr>
          <td><%= operation.name %></td>
          <td><%= operation.amount %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= @total_amount %>
<% else %>
  <p>No operations found.</p>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetMate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag asset_path('icon.png') %>
  </head>

  <body>
    <main class="flex flex-col items-center w-full bg-stone-50 h-screen">
      <%= render 'shared/navbar' %>
      <%= yield %>
      <% flash.each do |key, value| %>
        <% if key == "notice" %>
          <div class="alert alert-success flex flex-col content-center items-center" role="alert">
            <%= value %>
          </div>
        <% end %>
      <% end %>
    </main>
  </body>
</html>

app/views/operations/index.html.erb
<% @operations = @operations.sort_by { |operation| operation.created_at }.reverse %>

<div class="text-center text-white bg-sky-600 w-full leading-none">
  <h1>Most recent</h1>
  <p class="font-semibold">.</p>
</div>
<div class="flex justify-between w-full bg-white py-4 mb-2 font-semibold px-2">
  <span>Total:</span>
  <span>$<%= @total_amount %></span>
</div>
    <% @operations.each do |operation| %>
      <div class="grid grid-cols-3 w-full mb-2 py-3 overflow-x-hidden scrollbar-hide bg-white">
        <div class="text-4xl flex m-2 justify-center items-center bg-yellow-100 h-16 w-16 text-center">
          <%= @category.icon %>
        </div>
        <div class="flex flex-col justify-between">
          <p><%= operation.name %></p>
          <p class="text-xs"><%= operation.created_at.strftime('%B %d, %Y %H:%M') %></p>
        </div>
        <p class="flex justify-end font-semibold m-2"><%= number_to_currency(operation.amount) %></p>
      </div>
    <% end %>


<div class="fixed bottom-0 w-full bg-lime-600 text-center hover:bg-lime-700 py-6">
  <%= link_to 'New Transaction', new_operation_path(category_id: @category&.id), class: "text-white py-4 border-2 border-white", style: "padding-left: 29.5%; padding-right: 29.5%;" %>
</div>

app/views/operations/new.html.erb
<div class="flex flex-col items-center w-full">

<h1>New Operation</h1>

<%= form_with(model: @operation, local: true, html: { class: "w-full flex flex-col" }) do |form| %>
  <% if @operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
        <% @operation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: "Name", class: "mt-4 mb-2 block w-full border-1 border-slate-50 bg-white focus:ring focus:ring-gray-200 focus:ring-opacity-50" %>
  </div>

  <div class="field">
    <%= form.number_field :amount, placeholder: "$0.00", class: "mt-4 mb-2 block w-full border-1 border-slate-50 bg-white focus:ring focus:ring-gray-200 focus:ring-opacity-50" %>
  </div>

  <div class="field flex flex-col gap-1 m-2">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.where(user_id: current_user.id), :id, :name %>
  </div>


  <%= form.hidden_field :author_id, value: current_user.id %>

  <div class="actions fixed bottom-0 w-full bg-lime-600 text-center hover:bg-lime-600 py-2 text-white">
    <%= form.submit 'Save', class: 'text-white py-4 border-2 border-white', style: "padding-left: 43%; padding-right: 43%;" %>
  </div>
<% end %>

</div>

app/views/shared/_navbar.html.erb
<nav class="bg-sky-600 flex justify-between shadow w-full">
    <div class="flex items-center mx-2 w-full justify-between h-16">
    <%= link_to image_tag("back.png", width: 30), "/" %>
      <div class="flex items-center">
        <div class="flex-shrink-0 text-white">
          <%= @page_name %>
        </div>
      </div>
      <%= image_tag "search.png", width: 30 %>
  </div>
</nav>

app/views/users/index.html.erb
<div class="flex flex-col w-full items-center p-2 m-2">
  <h1 class="my-40"></h1>
  <%= image_tag "budgetmate.png", width: 200 %>
<div class="mb-20 w-full"></div>
<div class="mt-28 w-full">
  <a href="/users/sign_in" class="rounded relative inline-flex group items-center justify-center px-10 w-full py-2 cursor-pointer border-4 active:shadow-none shadow-lg bg-gradient-to-tr from-sky-600 to-sky-600 border-sky-600 text-white">
  <span class="relative">Log In</span>
  </a>
</div>
  
  <a href="/users/sign_up" class="rounded relative inline-flex group items-center justify-center px-10 w-full py-2 cursor-pointer bg-transparent text-gray">
  <span class="relative">Sign Up</span>
  </a>
</div>